// Generated by https://quicktype.io

class ActorDes {
  String birthday;
  String known_for_department;
  dynamic deathday;
  int id;
  String name;
  List<String> also_known_as;
  int gender;
  String biography;
  double popularity;
  String place_of_birth;
  String profile_path;
  bool adult;
  String imdb_id;
  String homepage;

  ActorDes({
    this.birthday,
    this.known_for_department,
    this.deathday,
    this.id,
    this.name,
    this.also_known_as,
    this.gender,
    this.biography,
    this.popularity,
    this.place_of_birth,
    this.profile_path,
    this.adult,
    this.imdb_id,
    this.homepage,
  });

  ActorDes.fromJSONMap(Map<String,dynamic>json){
    
    birthday                =json['birthday          '];
    known_for_department      =json['knownForDepartment'];
    deathday      =json['deathday'];
    id      =json['id'];
    name      =json['name'];
    also_known_as     =json['alsoKnownA'].cast<String>();
    gender      =json['gender'];
    biography     =json['biograph'];
    popularity      =json['popularity']/1;
    place_of_birth     =json['placeOfBirth'];
    profile_path     =json['profilePat'];
    adult     =json['adul'];
    imdb_id      =json['imdbId'];
    homepage      =json['homepage'];

  }
  getProfilePath(){
    if (profile_path == null) {
      return 'https://mantuatownship.com/wp-content/uploads/2018/01/no-results-empty-state.jpg';
    } else {
      return 'http://image.tmdb.org/t/p/w500/$profile_path';
    }
  }
}
